import * as vscode from "vscode";
import { PlaywrightCLITabViewCategory, PwCommand, CommandParameters } from "../helpers/types";

export function getPlaywrightCLICommandList(executeScript: (params?: CommandParameters) => Promise<void>): PwCommand[] {
  const commandsList: PwCommand[] = [
    {
      key: "installPlaywrightCLI",
      func: executeScript,
      prettyName: vscode.l10n.t("Install Playwright CLI"),
      category: PlaywrightCLITabViewCategory.installation,
      askForExecute: true,
      params: {
        key: "installPlaywrightCLI",
        command: "npm install @playwright/cli@latest",
        terminalName: vscode.l10n.t("Install Playwright CLI"),
      },
    },
    {
      key: "listLocalPlaywrightCLIPackageVersion",
      func: executeScript,
      prettyName: vscode.l10n.t("List Local Playwright CLI Package Version"),
      category: PlaywrightCLITabViewCategory.installation,
      askForExecute: true,
      params: {
        key: "listLocalPlaywrightCLIPackageVersion",
        command: "npm list --depth=0 @playwright/cli",
        terminalName: vscode.l10n.t("List Local Playwright CLI Package Version"),
      },
    },
    {
      key: "listGlobalPlaywrightCLIPackageVersion",
      func: executeScript,
      prettyName: vscode.l10n.t("List Global Playwright CLI Package Version"),
      category: PlaywrightCLITabViewCategory.installation,
      askForExecute: true,
      params: {
        key: "listGlobalPlaywrightCLIPackageVersion",
        command: "npm list -g --depth=0 @playwright/cli",
        terminalName: vscode.l10n.t("List Global Playwright CLI Package Version"),
      },
    },
    {
      key: "listPlaywrightCLIVersion",
      func: executeScript,
      prettyName: vscode.l10n.t("List Playwright CLI Version"),
      category: PlaywrightCLITabViewCategory.installation,
      askForExecute: true,
      params: {
        key: "listPlaywrightCLIVersion",
        command: "playwright-cli --version",
        terminalName: vscode.l10n.t("List Playwright CLI Version"),
      },
    },
    {
      key: "installPlaywrightCLIGlobally",
      func: executeScript,
      prettyName: vscode.l10n.t("Install Playwright CLI Globally"),
      category: PlaywrightCLITabViewCategory.installation,
      askForExecute: true,
      params: {
        key: "installPlaywrightCLIGlobally",
        command: "npm install -g @playwright/cli@latest",
        terminalName: vscode.l10n.t("Install Playwright CLI Globally"),
      },
    },
    {
      key: "initializePlaywrightCLIWorkspace",
      func: executeScript,
      prettyName: vscode.l10n.t("Initialize Playwright CLI Workspace"),
      category: PlaywrightCLITabViewCategory.installation,
      askForExecute: true,
      params: {
        key: "initializePlaywrightCLIWorkspace",
        command: "playwright-cli install",
        terminalName: vscode.l10n.t("Initialize Playwright CLI Workspace"),
      },
    },
    {
      key: "installPlaywrightCLISkills",
      func: executeScript,
      prettyName: vscode.l10n.t("Install Playwright CLI Skills"),
      category: PlaywrightCLITabViewCategory.installation,
      askForExecute: true,
      params: {
        key: "installPlaywrightCLISkills",
        command: "playwright-cli install --skills",
        terminalName: vscode.l10n.t("Install Playwright CLI Skills"),
      },
    },
    {
      key: "showPlaywrightCLIHelp",
      func: executeScript,
      prettyName: vscode.l10n.t("Show Playwright CLI Help"),
      category: PlaywrightCLITabViewCategory.installation,
      askForExecute: true,
      params: {
        key: "showPlaywrightCLIHelp",
        command: "playwright-cli --help",
        terminalName: vscode.l10n.t("Show Playwright CLI Help"),
      },
    },
    {
      key: "showPlaywrightCLIBrowserSessions",
      func: executeScript,
      prettyName: vscode.l10n.t("Show Playwright CLI Browser Sessions"),
      category: PlaywrightCLITabViewCategory.monitoring,
      askForExecute: true,
      params: {
        key: "showPlaywrightCLIBrowserSessions",
        command: "playwright-cli show",
        terminalName: vscode.l10n.t("Show Playwright CLI Browser Sessions"),
      },
    },
    {
      key: "playwrightCLIOpenBrowser",
      func: executeScript,
      prettyName: vscode.l10n.t("Open Browser in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      params: {
        key: "playwrightCLIOpenBrowser",
        command: "playwright-cli open",
        terminalName: vscode.l10n.t("Open Browser in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIOpenBrowserAtUrl",
      func: executeScript,
      prettyName: vscode.l10n.t("Open Browser at URL in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIOpenBrowserAtUrl",
        command: "playwright-cli open <url>",
        terminalName: vscode.l10n.t("Open Browser at URL in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIGotoUrl",
      func: executeScript,
      prettyName: vscode.l10n.t("Go to URL in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIGotoUrl",
        command: "playwright-cli goto <url>",
        terminalName: vscode.l10n.t("Go to URL in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIClosePage",
      func: executeScript,
      prettyName: vscode.l10n.t("Close Page in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      params: {
        key: "playwrightCLIClosePage",
        command: "playwright-cli close",
        terminalName: vscode.l10n.t("Close Page in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLITypeText",
      func: executeScript,
      prettyName: vscode.l10n.t("Type Text in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLITypeText",
        command: "playwright-cli type <text>",
        terminalName: vscode.l10n.t("Type Text in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIClick",
      func: executeScript,
      prettyName: vscode.l10n.t("Click Element in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIClick",
        command: "playwright-cli click <ref> [button]",
        terminalName: vscode.l10n.t("Click Element in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIDoubleClick",
      func: executeScript,
      prettyName: vscode.l10n.t("Double Click Element in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIDoubleClick",
        command: "playwright-cli dblclick <ref> [button]",
        terminalName: vscode.l10n.t("Double Click Element in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIFill",
      func: executeScript,
      prettyName: vscode.l10n.t("Fill Element in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIFill",
        command: "playwright-cli fill <ref> <text>",
        terminalName: vscode.l10n.t("Fill Element in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIDrag",
      func: executeScript,
      prettyName: vscode.l10n.t("Drag and Drop in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIDrag",
        command: "playwright-cli drag <startRef> <endRef>",
        terminalName: vscode.l10n.t("Drag and Drop in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIHover",
      func: executeScript,
      prettyName: vscode.l10n.t("Hover Element in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIHover",
        command: "playwright-cli hover <ref>",
        terminalName: vscode.l10n.t("Hover Element in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLISelect",
      func: executeScript,
      prettyName: vscode.l10n.t("Select Dropdown Option in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLISelect",
        command: "playwright-cli select <ref> <value>",
        terminalName: vscode.l10n.t("Select Dropdown Option in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIUpload",
      func: executeScript,
      prettyName: vscode.l10n.t("Upload File in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIUpload",
        command: "playwright-cli upload <file>",
        terminalName: vscode.l10n.t("Upload File in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLICheck",
      func: executeScript,
      prettyName: vscode.l10n.t("Check Element in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLICheck",
        command: "playwright-cli check <ref>",
        terminalName: vscode.l10n.t("Check Element in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIUncheck",
      func: executeScript,
      prettyName: vscode.l10n.t("Uncheck Element in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIUncheck",
        command: "playwright-cli uncheck <ref>",
        terminalName: vscode.l10n.t("Uncheck Element in Playwright CLI"),
      },
    },
    {
      key: "snapshotPlaywrightCLIBrowser",
      func: executeScript,
      prettyName: vscode.l10n.t("Snapshot Playwright CLI Browser"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      params: {
        key: "snapshotPlaywrightCLIBrowser",
        command: "playwright-cli snapshot",
        terminalName: vscode.l10n.t("Snapshot Playwright CLI Browser"),
      },
    },
    {
      key: "snapshotPlaywrightCLIBrowserToFile",
      func: executeScript,
      prettyName: vscode.l10n.t("Save Playwright CLI Snapshot to File"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "snapshotPlaywrightCLIBrowserToFile",
        command: "playwright-cli snapshot --filename=<filename>",
        terminalName: vscode.l10n.t("Save Playwright CLI Snapshot to File"),
      },
    },
    {
      key: "playwrightCLIEval",
      func: executeScript,
      prettyName: vscode.l10n.t("Evaluate JavaScript in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIEval",
        command: "playwright-cli eval <func> [ref]",
        terminalName: vscode.l10n.t("Evaluate JavaScript in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIDialogAccept",
      func: executeScript,
      prettyName: vscode.l10n.t("Accept Dialog in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIDialogAccept",
        command: "playwright-cli dialog-accept [prompt]",
        terminalName: vscode.l10n.t("Accept Dialog in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIDialogDismiss",
      func: executeScript,
      prettyName: vscode.l10n.t("Dismiss Dialog in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      params: {
        key: "playwrightCLIDialogDismiss",
        command: "playwright-cli dialog-dismiss",
        terminalName: vscode.l10n.t("Dismiss Dialog in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIResizeWindow",
      func: executeScript,
      prettyName: vscode.l10n.t("Resize Browser Window in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.core,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIResizeWindow",
        command: "playwright-cli resize <width> <height>",
        terminalName: vscode.l10n.t("Resize Browser Window in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIGoBack",
      func: executeScript,
      prettyName: vscode.l10n.t("Go Back in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.navigation,
      askForExecute: true,
      params: {
        key: "playwrightCLIGoBack",
        command: "playwright-cli go-back",
        terminalName: vscode.l10n.t("Go Back in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIGoForward",
      func: executeScript,
      prettyName: vscode.l10n.t("Go Forward in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.navigation,
      askForExecute: true,
      params: {
        key: "playwrightCLIGoForward",
        command: "playwright-cli go-forward",
        terminalName: vscode.l10n.t("Go Forward in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIReload",
      func: executeScript,
      prettyName: vscode.l10n.t("Reload Page in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.navigation,
      askForExecute: true,
      params: {
        key: "playwrightCLIReload",
        command: "playwright-cli reload",
        terminalName: vscode.l10n.t("Reload Page in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIPressKey",
      func: executeScript,
      prettyName: vscode.l10n.t("Press Key in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.keyboard,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIPressKey",
        command: "playwright-cli press <key>",
        terminalName: vscode.l10n.t("Press Key in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIKeyDown",
      func: executeScript,
      prettyName: vscode.l10n.t("Key Down in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.keyboard,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIKeyDown",
        command: "playwright-cli keydown <key>",
        terminalName: vscode.l10n.t("Key Down in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIKeyUp",
      func: executeScript,
      prettyName: vscode.l10n.t("Key Up in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.keyboard,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIKeyUp",
        command: "playwright-cli keyup <key>",
        terminalName: vscode.l10n.t("Key Up in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIMouseMove",
      func: executeScript,
      prettyName: vscode.l10n.t("Move Mouse in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.mouse,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIMouseMove",
        command: "playwright-cli mousemove <x> <y>",
        terminalName: vscode.l10n.t("Move Mouse in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIMouseDown",
      func: executeScript,
      prettyName: vscode.l10n.t("Mouse Down in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.mouse,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIMouseDown",
        command: "playwright-cli mousedown [button]",
        terminalName: vscode.l10n.t("Mouse Down in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIMouseUp",
      func: executeScript,
      prettyName: vscode.l10n.t("Mouse Up in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.mouse,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIMouseUp",
        command: "playwright-cli mouseup [button]",
        terminalName: vscode.l10n.t("Mouse Up in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIMouseWheel",
      func: executeScript,
      prettyName: vscode.l10n.t("Mouse Wheel in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.mouse,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIMouseWheel",
        command: "playwright-cli mousewheel <dx> <dy>",
        terminalName: vscode.l10n.t("Mouse Wheel in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIScreenshot",
      func: executeScript,
      prettyName: vscode.l10n.t("Take Screenshot in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.saveAs,
      askForExecute: true,
      params: {
        key: "playwrightCLIScreenshot",
        command: "playwright-cli screenshot",
        terminalName: vscode.l10n.t("Take Screenshot in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIScreenshotElement",
      func: executeScript,
      prettyName: vscode.l10n.t("Take Element Screenshot in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.saveAs,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIScreenshotElement",
        command: "playwright-cli screenshot [ref]",
        terminalName: vscode.l10n.t("Take Element Screenshot in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIScreenshotToFile",
      func: executeScript,
      prettyName: vscode.l10n.t("Save Screenshot to File in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.saveAs,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIScreenshotToFile",
        command: "playwright-cli screenshot --filename=<filename>",
        terminalName: vscode.l10n.t("Save Screenshot to File in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIPDF",
      func: executeScript,
      prettyName: vscode.l10n.t("Save PDF in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.saveAs,
      askForExecute: true,
      params: {
        key: "playwrightCLIPDF",
        command: "playwright-cli pdf",
        terminalName: vscode.l10n.t("Save PDF in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIPDFToFile",
      func: executeScript,
      prettyName: vscode.l10n.t("Save PDF to File in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.saveAs,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIPDFToFile",
        command: "playwright-cli pdf --filename=<filename>",
        terminalName: vscode.l10n.t("Save PDF to File in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLITabList",
      func: executeScript,
      prettyName: vscode.l10n.t("List Tabs in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.tabs,
      askForExecute: true,
      params: {
        key: "playwrightCLITabList",
        command: "playwright-cli tab-list",
        terminalName: vscode.l10n.t("List Tabs in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLITabNew",
      func: executeScript,
      prettyName: vscode.l10n.t("Open New Tab in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.tabs,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLITabNew",
        command: "playwright-cli tab-new [url]",
        terminalName: vscode.l10n.t("Open New Tab in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLITabClose",
      func: executeScript,
      prettyName: vscode.l10n.t("Close Tab in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.tabs,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLITabClose",
        command: "playwright-cli tab-close [index]",
        terminalName: vscode.l10n.t("Close Tab in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLITabSelect",
      func: executeScript,
      prettyName: vscode.l10n.t("Select Tab in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.tabs,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLITabSelect",
        command: "playwright-cli tab-select <index>",
        terminalName: vscode.l10n.t("Select Tab in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIStateSave",
      func: executeScript,
      prettyName: vscode.l10n.t("Save Storage State in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIStateSave",
        command: "playwright-cli state-save [filename]",
        terminalName: vscode.l10n.t("Save Storage State in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIStateLoad",
      func: executeScript,
      prettyName: vscode.l10n.t("Load Storage State in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIStateLoad",
        command: "playwright-cli state-load <filename>",
        terminalName: vscode.l10n.t("Load Storage State in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLICookieList",
      func: executeScript,
      prettyName: vscode.l10n.t("List Cookies in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLICookieList",
        command: "playwright-cli cookie-list [--domain]",
        terminalName: vscode.l10n.t("List Cookies in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLICookieGet",
      func: executeScript,
      prettyName: vscode.l10n.t("Get Cookie in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLICookieGet",
        command: "playwright-cli cookie-get <name>",
        terminalName: vscode.l10n.t("Get Cookie in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLICookieSet",
      func: executeScript,
      prettyName: vscode.l10n.t("Set Cookie in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLICookieSet",
        command: "playwright-cli cookie-set <name> <value>",
        terminalName: vscode.l10n.t("Set Cookie in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLICookieDelete",
      func: executeScript,
      prettyName: vscode.l10n.t("Delete Cookie in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLICookieDelete",
        command: "playwright-cli cookie-delete <name>",
        terminalName: vscode.l10n.t("Delete Cookie in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLICookieClear",
      func: executeScript,
      prettyName: vscode.l10n.t("Clear Cookies in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      params: {
        key: "playwrightCLICookieClear",
        command: "playwright-cli cookie-clear",
        terminalName: vscode.l10n.t("Clear Cookies in Playwright CLI"),
      },
    },
    {
      key: "listPlaywrightCLIBrowserLocalStorage",
      func: executeScript,
      prettyName: vscode.l10n.t("List Playwright CLI Browser Local Storage"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      params: {
        key: "listPlaywrightCLIBrowserLocalStorage",
        command: "playwright-cli localstorage-list",
        terminalName: vscode.l10n.t("List Playwright CLI Browser Local Storage"),
      },
    },
    {
      key: "playwrightCLILocalStorageGet",
      func: executeScript,
      prettyName: vscode.l10n.t("Get Local Storage Value in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLILocalStorageGet",
        command: "playwright-cli localstorage-get <key>",
        terminalName: vscode.l10n.t("Get Local Storage Value in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLILocalStorageSet",
      func: executeScript,
      prettyName: vscode.l10n.t("Set Local Storage Value in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLILocalStorageSet",
        command: "playwright-cli localstorage-set <key> <value>",
        terminalName: vscode.l10n.t("Set Local Storage Value in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLILocalStorageDelete",
      func: executeScript,
      prettyName: vscode.l10n.t("Delete Local Storage Value in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLILocalStorageDelete",
        command: "playwright-cli localstorage-delete <key>",
        terminalName: vscode.l10n.t("Delete Local Storage Value in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLILocalStorageClear",
      func: executeScript,
      prettyName: vscode.l10n.t("Clear Local Storage in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      params: {
        key: "playwrightCLILocalStorageClear",
        command: "playwright-cli localstorage-clear",
        terminalName: vscode.l10n.t("Clear Local Storage in Playwright CLI"),
      },
    },
    {
      key: "listPlaywrightCLIBrowserSessionStorage",
      func: executeScript,
      prettyName: vscode.l10n.t("List Playwright CLI Browser Session Storage"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      params: {
        key: "listPlaywrightCLIBrowserSessionStorage",
        command: "playwright-cli sessionstorage-list",
        terminalName: vscode.l10n.t("List Playwright CLI Browser Session Storage"),
      },
    },
    {
      key: "playwrightCLISessionStorageGet",
      func: executeScript,
      prettyName: vscode.l10n.t("Get Session Storage Value in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLISessionStorageGet",
        command: "playwright-cli sessionstorage-get <key>",
        terminalName: vscode.l10n.t("Get Session Storage Value in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLISessionStorageSet",
      func: executeScript,
      prettyName: vscode.l10n.t("Set Session Storage Value in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLISessionStorageSet",
        command: "playwright-cli sessionstorage-set <key> <value>",
        terminalName: vscode.l10n.t("Set Session Storage Value in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLISessionStorageDelete",
      func: executeScript,
      prettyName: vscode.l10n.t("Delete Session Storage Value in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLISessionStorageDelete",
        command: "playwright-cli sessionstorage-delete <key>",
        terminalName: vscode.l10n.t("Delete Session Storage Value in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLISessionStorageClear",
      func: executeScript,
      prettyName: vscode.l10n.t("Clear Session Storage in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.storage,
      askForExecute: true,
      params: {
        key: "playwrightCLISessionStorageClear",
        command: "playwright-cli sessionstorage-clear",
        terminalName: vscode.l10n.t("Clear Session Storage in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIRoute",
      func: executeScript,
      prettyName: vscode.l10n.t("Create Network Route in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.network,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIRoute",
        command: "playwright-cli route <pattern> [options]",
        terminalName: vscode.l10n.t("Create Network Route in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIListActiveRoutes",
      func: executeScript,
      prettyName: vscode.l10n.t("List Active Routes in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.network,
      askForExecute: true,
      params: {
        key: "playwrightCLIListActiveRoutes",
        command: "playwright-cli route-list",
        terminalName: vscode.l10n.t("List Active Routes in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIUnroute",
      func: executeScript,
      prettyName: vscode.l10n.t("Remove Route in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.network,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIUnroute",
        command: "playwright-cli unroute [pattern]",
        terminalName: vscode.l10n.t("Remove Route in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIConsole",
      func: executeScript,
      prettyName: vscode.l10n.t("List Console Messages in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.devTools,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIConsole",
        command: "playwright-cli console [min-level]",
        terminalName: vscode.l10n.t("List Console Messages in Playwright CLI"),
      },
    },
    {
      key: "listPlaywrightCLIBrowserNetworkRequests",
      func: executeScript,
      prettyName: vscode.l10n.t("List Playwright CLI Browser Network Requests"),
      category: PlaywrightCLITabViewCategory.devTools,
      askForExecute: true,
      params: {
        key: "listPlaywrightCLIBrowserNetworkRequests",
        command: "playwright-cli network",
        terminalName: vscode.l10n.t("List Playwright CLI Browser Network Requests"),
      },
    },
    {
      key: "playwrightCLIRunCode",
      func: executeScript,
      prettyName: vscode.l10n.t("Run Playwright Code Snippet in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.devTools,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIRunCode",
        command: "playwright-cli run-code <code>",
        terminalName: vscode.l10n.t("Run Playwright Code Snippet in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLICaptureTrace",
      func: executeScript,
      prettyName: vscode.l10n.t("Start Trace Recording in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.devTools,
      askForExecute: true,
      params: {
        key: "playwrightCLICaptureTrace",
        command: "playwright-cli tracing-start",
        terminalName: vscode.l10n.t("Start Trace Recording in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIStopTrace",
      func: executeScript,
      prettyName: vscode.l10n.t("Stop Trace Recording in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.devTools,
      askForExecute: true,
      params: {
        key: "playwrightCLIStopTrace",
        command: "playwright-cli tracing-stop",
        terminalName: vscode.l10n.t("Stop Trace Recording in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLICaptureVideo",
      func: executeScript,
      prettyName: vscode.l10n.t("Start Video Recording in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.devTools,
      askForExecute: true,
      params: {
        key: "playwrightCLICaptureVideo",
        command: "playwright-cli video-start",
        terminalName: vscode.l10n.t("Start Video Recording in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIStopVideo",
      func: executeScript,
      prettyName: vscode.l10n.t("Stop Video Recording in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.devTools,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIStopVideo",
        command: "playwright-cli video-stop [filename]",
        terminalName: vscode.l10n.t("Stop Video Recording in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIOpenWithBrowser",
      func: executeScript,
      prettyName: vscode.l10n.t("Open Browser with Specific Engine in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.openParameters,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIOpenWithBrowser",
        command: "playwright-cli open --browser=<browser>",
        terminalName: vscode.l10n.t("Open Browser with Specific Engine in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIOpenWithExtension",
      func: executeScript,
      prettyName: vscode.l10n.t("Open Browser Using Extension in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.openParameters,
      askForExecute: true,
      params: {
        key: "playwrightCLIOpenWithExtension",
        command: "playwright-cli open --extension",
        terminalName: vscode.l10n.t("Open Browser Using Extension in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIOpenPersistent",
      func: executeScript,
      prettyName: vscode.l10n.t("Open Browser with Persistent Profile in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.openParameters,
      askForExecute: true,
      params: {
        key: "playwrightCLIOpenPersistent",
        command: "playwright-cli open --persistent",
        terminalName: vscode.l10n.t("Open Browser with Persistent Profile in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIOpenWithProfilePath",
      func: executeScript,
      prettyName: vscode.l10n.t("Open Browser with Profile Path in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.openParameters,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIOpenWithProfilePath",
        command: "playwright-cli open --profile=<path>",
        terminalName: vscode.l10n.t("Open Browser with Profile Path in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIOpenWithConfig",
      func: executeScript,
      prettyName: vscode.l10n.t("Open Browser with Config File in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.openParameters,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIOpenWithConfig",
        command: "playwright-cli open --config=<file.json>",
        terminalName: vscode.l10n.t("Open Browser with Config File in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIDeleteData",
      func: executeScript,
      prettyName: vscode.l10n.t("Delete Session Data in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.openParameters,
      askForExecute: true,
      params: {
        key: "playwrightCLIDeleteData",
        command: "playwright-cli delete-data",
        terminalName: vscode.l10n.t("Delete Session Data in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIRunCommandInNamedSession",
      func: executeScript,
      prettyName: vscode.l10n.t("Run Command in Named Session in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.sessions,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIRunCommandInNamedSession",
        command: "playwright-cli -s=<name> <cmd>",
        terminalName: vscode.l10n.t("Run Command in Named Session in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLICloseNamedSession",
      func: executeScript,
      prettyName: vscode.l10n.t("Close Named Session in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.sessions,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLICloseNamedSession",
        command: "playwright-cli -s=<name> close",
        terminalName: vscode.l10n.t("Close Named Session in Playwright CLI"),
      },
    },
    {
      key: "playwrightCLIDeleteNamedSessionData",
      func: executeScript,
      prettyName: vscode.l10n.t("Delete Named Session Data in Playwright CLI"),
      category: PlaywrightCLITabViewCategory.sessions,
      askForExecute: true,
      onlyPaste: true,
      params: {
        key: "playwrightCLIDeleteNamedSessionData",
        command: "playwright-cli -s=<name> delete-data",
        terminalName: vscode.l10n.t("Delete Named Session Data in Playwright CLI"),
      },
    },
    {
      key: "listPlaywrightCLIBrowserSessions",
      func: executeScript,
      prettyName: vscode.l10n.t("List Playwright CLI Browser Sessions"),
      category: PlaywrightCLITabViewCategory.sessions,
      askForExecute: true,
      params: {
        key: "listPlaywrightCLIBrowserSessions",
        command: "playwright-cli list",
        terminalName: vscode.l10n.t("List Playwright CLI Browser Sessions"),
      },
    },
    {
      key: "closeAllPlaywrightCLIBrowserSessions",
      func: executeScript,
      prettyName: vscode.l10n.t("Close All Playwright CLI Browser Sessions"),
      category: PlaywrightCLITabViewCategory.sessions,
      askForExecute: true,
      params: {
        key: "closeAllPlaywrightCLIBrowserSessions",
        command: "playwright-cli close-all",
        terminalName: vscode.l10n.t("Close All Playwright CLI Browser Sessions"),
      },
    },
    {
      key: "killAllPlaywrightCLIBrowserSessions",
      func: executeScript,
      prettyName: vscode.l10n.t("Kill All Playwright CLI Browser Sessions"),
      category: PlaywrightCLITabViewCategory.sessions,
      askForExecute: true,
      params: {
        key: "killAllPlaywrightCLIBrowserSessions",
        command: "playwright-cli kill-all",
        terminalName: vscode.l10n.t("Kill All Playwright CLI Browser Sessions"),
      },
    },
  ];
  return commandsList;
}
