name: Feature Request 🚀
description: Submit a proposal for a new feature
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for taking the time to suggest a new feature!
  - type: textarea
    id: description
    attributes:
      label: "🚀 Feature Request"
      description: A clear and concise description of the feature you are proposing.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example
      description: Describe a use case for the feature you are proposing.
    validations:
      required: false
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        Why do you think this feature is important?
        What are you trying to accomplish?
    validations:
      required: true
